SELECT *
FROM Amazon2

ALTER TABLE Amazon2
ALTER COLUMN Selling_Price Decimal(10,2)

ALTER TABLE Amazon2
ALTER COLUMN Tax_5 Decimal(10,2)

--TOTAL REVENUE GENERATED BY EACH BRANCH
SELECT Branch,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
From Amazon2
GROUP BY Branch

--TOP 3 PRODUCT LINES BY REVENUE
SELECT TOP 3 Product_line,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
GROUP BY Product_line
ORDER BY Total_Revenue DESC

--TOTAL REVENUE BY CUSTOMER TYPE
SELECT Customer_type,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
GROUP BY Customer_type

--AVERAGE RATING FOR EACH PRODUCT LINE
SELECT Product_line,
AVG(Rating) AS Average_Rating
FROM Amazon2
GROUP BY Product_line

ALTER TABLE Amazon2
ALTER COLUMN Rating Decimal(10,2)

--REVENUE GENERATED PER PAYMENT METHOD

SELECT Payment,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
GROUP BY Payment
ORDER BY Total_Revenue Desc

--DAILY REVENUE TREND

SELECT DATE,
SUM((Selling_Price * Quantity) + Tax_5) AS Daily_Revenue
FROM Amazon2
GROUP BY Date
ORDER BY Date DESC




